CREATE Table AUX (
	a integer
);
INSERT INTO AUX VALUES (1)


SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

BEGIN TRANSACTION

UPDATE AUX SET a = (SELECT stars FROM HOTELS WHERE hotel_id = 1006)
SELECT * FROM AUX

UPDATE HOTELS SET stars = a + 1 FROM AUX WHERE hotel_id = 1006

COMMIT

SELECT stars FROM HOTELS WHERE hotel_id = 1006
UPDATE HOTELS SET stars = 3 WHERE hotel_id = 1006

DROP TABLE AUX
